---

# List of yum repositories.
# e.g.
# common_repos:
#  - name: name
#    config:
#      key: value
#      .
#      .
common_repos:
  - name: base
    config:
      name: CentOS-$releasever - Base
      mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra
      '#baseurl': http://mirror.centos.org/centos/$releasever/os/$basearch/
      gpgcheck: 1
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
  - name: updates
    config:
      name: CentOS-$releasever - Updates
      mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates&infra=$infra
      '#baseurl': http://mirror.centos.org/centos/$releasever/updates/$basearch/
      gpgcheck: 1
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
  - name: extras
    config:
      name: CentOS-$releasever - Extras
      mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras&infra=$infra
      '#baseurl': http://mirror.centos.org/centos/$releasever/extras/$basearch/
      gpgcheck: 1
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7


# List of package names to be installed.
# e.g.
# common_packages:
#  - lsscsi
#  - ltrace
#  - strace
common_packages: []


# Root and user shell prompts.
common_prompt_root: '\h# '
common_prompt_user: '\h$ '


# List of user dictionaries for group and user creation.
# e.g.
# common_usersgroups:
#  - name: user
#    state: present
#    uid: 1000
#    gid: 1000
#    groups: [ wheel, libvirt, docker ]
#    comment: User
#    home: /home/user
#    shell: /bin/bash
#    password: '$6$...$...'
common_usersgroups: []
