---

- name: Package dependencies
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2


- name: Repositories
  template:
    src: yum.repo.j2
    dest: "/etc/yum.repos.d/{{ item.name }}.repo"
    owner: root
    group: root
    mode: 0644
  with_items:
    "{{ docker_repos }}"


- name: Package
  yum:
    name: docker-ce
    state: latest


- name: Service
  service:
    name: docker
    state: started
