---

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance-common
    image: centos:7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: [ "ANSIBLE0010" ]
scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
    options:
      ignore: E111, E121, E126, E201, E202
